### ISSUE TITLE
OpenHydraulics in OpenModelica

### ISSUE THREAD

**Issue by joehays** [modelica-3rdparty/OpenHydraulics#12]
Hello,

I'm a brand new Modelica user. I'm trying to learn the language with OpenModelica. I'd like to use OpenHydraulics in OpenModelica (specifically in the OMEdit Connection Editor). I downloaded version 1.0.1 of OpenHydraulics and installed it in "~OpenModelica1.0.0\lib\omlibrary\OpenHydraulics 1.0.1". I added this library in the OMEdit library list. After relaunching OMEdit I do see the OpenHydraulics library and am able to browse the library, however, when I open the Excavator example and try to Instantiate or Simulate the model I get many errors of the form:

"Base class Modelica.Icons.ExamplesPackage not found in scope OpenHydraulics.Examples"

I "installed" OpenHydraulics from the .zip that I downloaded from GITHUB. I had to modify the folder name and pull the code up one folder level to get OMEdit to recognize it and allow me to browse it (meaning from "~OpenModelica1.0.0\lib\omlibrary\OpenHydraulics 1.0.1\OpenHydraulics" to "~OpenModelica1.0.0\lib\omlibrary\OpenHydraulics 1.0.1"). However, with the above errors it seems that I've not installed this correctly. 

Are there some simple instructions to properly install OpenHydraulics in OpenModelica such that I can run the Excavator example in the OMEdit Connection Editor tool?

Thanks in advance.

**Comment by vwaurich** [comment]
Recently, OpenModelica overcame its problems with [OpenHydraulics](https://test.openmodelica.org/libraries/history/OpenHydraulics/OpenHydraulics-2017-03-10.html).
