### ISSUE TITLE
Problems using OpenHydraulics

### ISSUE THREAD

**Issue by JanZepp** [modelica-3rdparty/OpenHydraulics#18]
Hello,

I just started using Modelica and OpenHydraulics and have the following Problems:
- lots of the examples (Folder circuits) don't work. It seems that there are more variables than equations
- I can't connect junction components (neither graphically nor by adding the code manually)
- using the circuitTank always leads to a error message like "V_actual < V_max"

Does an "Manual" (which describes the equations used and how to use the components) for this library exist?

I apologise for my bad English. Thank you very much
Regards, Jan

**Comment by xogeny** [comment]
It would help if you indicated which Modelica tool you are using to compile and what models you are attempting to run.

**Comment by JanZepp** [comment]
Youre right, sorry. 
I am using OMEdit (should be ne newest Version).
Models that don't work:
- PressureCompensated
- PressureCompensatedLoadSensing
- Regenerative
- OpenCenter
- OpenCenter_tandem
- OpenCenterForceVelocityControl
- OpenCenterSectionalValveCircuit
So, obviously, all of them don't work. The error message is always the same. I can check the model and everything seems to be alright, but when I run the model, the error "more variables than equations" occours.

The junction element I mentioned can be found under Components > Lines > NJunction. I chose n_ports = 3 but there is no possibilty to connect the junction to anything else.

**Comment by dietmarw** [comment]
I'm afraid this might be (partly) down to OMC not supporting all Modelica features yet. You can find a detailed status of the library coverage on OM's test coverage page of this library: https://test.openmodelica.org/libraries/OpenHydraulics/BuildModelRecursive.html

**Comment by JanZepp** [comment]
Thank you for this hint.
Do you know if it could be similar with the junctions? 
In the provided examples, junctions are used to split or combine several massflows. It may sound curious but I can't connect these junctions to other components. If i try to define the connection by clicking on the (e.g.) pump port at first and then on the junction, nothing happens (the line doesn't lock). So I tried to add the equations manually, e.g. connect(pump.portP, j1.port[1]) but it wasn't succesful, too.

**Comment by JanZepp** [comment]
This Problem is solved now.
At first, I had to add the code manually (connect(tank1.port, j1.port[1])), afterwards, the connection can be done and the code, that was added manually can be removed again. Not very nice but it works

**Comment by cparedis** [comment]
Jan: 
Sorry to hear that you are running into problems. When the library was developed several years ago, it was tested with Dymola and everything worked well (to the best of my knowledge). I do know that the library relies on language features that are not yet fully supported by OpenModelica -- but I believe the library is part of their test suite and that they are working on it. Unfortunately, in my current position, I don't really have the time to debug the library further, especially not in a variety of different tools. I hope you understand. 

** Chris ** 

Chris Paredis 
Professor of Mechanical Engineering, Woodruff Faculty Fellow 
Georgia Institute of Technology 
The G.W. Woodruff School of Mechanical Engineering 
The H.M. Stewart School of Industrial and Systems Engineering 
Director, Model-Based Systems Engineering Center 
813 Ferst Drive, MARC Rm. 256 
Atlanta, GA 30332-0405 
E-mail: chris.paredis@me.gatech.edu 
Phone: +1 (404) 894-5613 
http://www.mbsec.gatech.edu/users/cparedis/Calendar 
Assistant: Lynette McLeod, +1 (404) 894-0413 

----- Original Message -----

**Comment by JanZepp** [comment]
Thank you very much for the quick support! OM seems to have a great community :+1: 
I think it will be the best to start creating my own library that consists only of the elements I really need. And also for this task, the OpenHydraulics-library is a good guide.

So, thanks again. Jan

**Comment by cparedis** [comment]
Great. Yes, feel free to borrow any part of the library you feel will help your effort. 

** Chris ** 

Chris Paredis 
Professor of Mechanical Engineering, Woodruff Faculty Fellow 
Georgia Institute of Technology 
The G.W. Woodruff School of Mechanical Engineering 
The H.M. Stewart School of Industrial and Systems Engineering 
Director, Model-Based Systems Engineering Center 
813 Ferst Drive, MARC Rm. 256 
Atlanta, GA 30332-0405 
E-mail: chris.paredis@me.gatech.edu 
Phone: +1 (404) 894-5613 
http://www.mbsec.gatech.edu/users/cparedis/Calendar 
Assistant: Lynette McLeod, +1 (404) 894-0413 

----- Original Message -----
