### ISSUE TITLE
Library information

### ISSUE THREAD

**Issue by Edwin-Avila** [modelica-3rdparty/OpenHydraulics#19]
Hello,

I'm completely new in modelica and I crossed along this librar that I think it's very useful for what I need to do. I was just wondering if there's a publication where I can find deeper information about the library (article, book, blog).

Thank you very much for your help.
Edwin Avila

**Comment by xogeny** [comment]
@Edwin-Avila The library was original created by @cparedis.  But it seems to be in a maintenance mode now.  I'm not aware of any publications on the library (apart from the documentation in the models themselves).  You may also be interested in the `Modelica.Fluid` and `Modelica.Media` libraries.  But they are, in my opinion, more complicated than `OpenHydraulics`.  The advantages of those libraries are that they are a) part of the Modelica Standard Library, b) can handle incompressible flow, c) have had papers and presentations given about them and d) use the new `stream` functionality in Modelica to handle intensive properties of the flow.

**Comment by Edwin-Avila** [comment]
@xogeny Ok got ir, thank you very much for your reply. I'll check the other libraries you mentioned.
