### ISSUE TITLE
OpenHydraulics v1.0.1 in OpenModelica v1.19.2 with Modelica Standard Lib v3.2

### ISSUE THREAD

**Issue by computational-physcis-2011301020083** [modelica-3rdparty/OpenHydraulics#20]
Hello,

I'm a brand new Modelica user. I'm trying to learn the language with OpenModelica. I'd like to use OpenHydraulics in OpenModelica (specifically in the OMEdit Connection Editor). 

I downloaded OpenModelica v1.19.2 and Modelica Standard Lib v3.2 to browse and run the library OpenHydraulics v1.0.1. However, when I open the Excavator example and try to Instantiate or Simulate the model I get many errors of the form:

**[OpenHydraulics.Basic.VariableRestriction: 51:3-54:64]: [Function ReynoldsNumber_m_flow not found in scope VariableRestriction.](omeditmessagesbrowser:///OpenHydraulics.Basic.VariableRestriction?lineNumber=51)**

Could you help me with this problem?
Thanks in advance.

**Comment by mtiller** [comment]
Your best bet is to ask the OpenModelica folks and/or post your question on StackOverflow with the “Modelica” tag.

**Comment by computational-physcis-2011301020083** [comment]
Thank you !
