### ISSUE TITLE
Parameter description typo of Partial Fluid Component

### ISSUE THREAD

**Issue by jung40l** [modelica-3rdparty/OpenHydraulics#22]
There is a typo in the description of the parameter p_init of PartialFluidComponent.
I think the description of p_init should be corrected to "Atmosperic Pressure".

Thanks for providing a useful library.

----------------------------------------------
within OpenHydraulics.Interfaces;
partial model **PartialFluidComponent**
  "Base model for any component involving fluid"

  outer OpenHydraulics.Fluids.BaseClasses.PartialFluid oil
    "This model must be defined in each circuit; the type must be a subtype of PartialFluid";

  parameter SI.AbsolutePressure **p_init** = environment.p_ambient
    "**Initial temperature of the component**" annotation (Dialog(tab="Initialization",group="Fluid"));

protected
  outer OpenHydraulics.Circuits.Environment environment;

end PartialFluidComponent;

----------------------------------------------

**Comment by dietmarw** [comment]
Thanks. I fixed this in https://github.com/modelica-3rdparty/OpenHydraulics/commit/d7832e6af944702db67c4a23bbbb3b429c272dde but slightly different than you suggested.

**Comment by jung40l** [comment]
Thanks for the quick fix!

**Comment by pidou46** [comment]
Hello,
The same apply to "doubleActingCylinder", comment for p_init is "Initial temperature of the component" should be "Initial pressure  of the component"

**Comment by dietmarw** [comment]
I'm sorry I fail to see that in the latest code base.
